### ISSUE TITLE
激活失败

### ISSUE THREAD

**Issue by luqin2007** [DiamondHunters/NodeInject#3]
版本：1.8.10，Windows 11
提示信息：

1. 在 Typora 根目录运行编译出的 node_inject.exe 后提示 
```
extracting node_modules.asar
adding hook.js
applying patch
packing node_modules.asar
done!
```
重复运行提示 `You may have already installed the hook.Please check manually.`

2. 在 `NodeInject_Hook_example\license-gen` 下运行 `cargo run` 能生成激活码
```
License for you: H5JJNE-8CD4RJ-QCGBZG-6PN95Q
```

3. 打开 Typora，使用任意 Email 和刚刚生成的序列号激活，提示请输入正确的序列号

**Comment by mcitem** [comment]
请配合使用`https://github.com/DiamondHunters/NodeInject_Hook_example`

**Comment by luqin2007** [comment]
> 请配合使用`https://github.com/DiamondHunters/NodeInject_Hook_example`

就是配合使用这个啊，生成激活码，`hook.js` 也替换了

**Comment by mcitem** [comment]
https://wwsj.lanzout.com/b0fhjolfc
如果只是为了激活，可以直接使用编译的exe
密码 hnlm

**Comment by luqin2007** [comment]
> https://wwsj.lanzout.com/b0fhjolfc 如果只是为了激活，可以直接使用编译的exe 密码 hnlm

ok这个可用
